version: '3'
services:
  backend:
    build: ./backend
    container_name: py-backend
    ports:
      - "6789:6789"
  frontend:
    build: ./frontend
    container_name: vite-frontend
    ports:
      - "3000:80"